CREATE TABLE `book` (
  `bookid` INT(9) NOT NULL AUTO_INCREMENT,
  `bookname` VARCHAR(64) NOT NULL,
  `bookcontent` VARCHAR(10240) DEFAULT NULL,
  `bookwebid` VARCHAR(128) DEFAULT NULL,
  `chaptername` VARCHAR(128) DEFAULT NULL,
  `createtime` DATETIME NOT NULL,
  PRIMARY KEY (`bookid`)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8

